### ISSUE TITLE
Feature request: Additional sorting functions

### ISSUE THREAD

**Issue by hacfi** [mmoreram/php-formatter#10]
I would like to suggest some new features for the sorter:
- [ ] add an option to put the extended class + interfaces at the top (or top of the group)
- [ ] create a special group name `_annotations` which groups annotations (is that possible with the current implementation/in general?)
- [x] allow to combine groups like:

```yml
use-sort:
    group:
        - Symfony
        - _main
        - App
        - ['Sensio\Bundle\FrameworkExtraBundle\Configuration', 'JMS\DiExtraBundle\Annotation']
    group-type: each
    sort-type: alph
    sort-direction: asc
```

- [x] and ideally allow additional sorting within a group (like Symfony HttpKernel before Symfony Form e.g.)

Wdyt @mmoreram ?
