### ISSUE TITLE
Grouping use-statements sometimes leaves gaps

### ISSUE THREAD

**Issue by matt-usurp** [mmoreram/php-formatter#24]
I have been noticing this issue often and have been meaning to attempt to fix it. I haven't had time and I keep forgetting so I am creating this issue as a kind of reminder. Also hoping that someone will know exactly why this is happening and be able to submit a fix faster than me.

It looks like when sorting use-statements in fairly complex groups and two groups consecutively are not being used there are some additional spaces added.

Example pulled from my test classes.
```php
use Project\Core\AClass;
use Project\Core\BClass;
use Project\Core\CClass;



use PHPUnit_Framework_MockObject_MockObject as MockObject;
```

With the following configuration:
```yaml
use-sort:
  group:
    - Project\Core
    - Project\Integration
    - [Symfony, Sensio, Doctrine]
    - _main
  group-type: each
  group-skip-empty: true
  sort-type: alph
  sort-direction: asc
```

**Please note** that `group-skip-empty` is enabled also.

Expecting output:
```php
use Project\Core\AClass;
use Project\Core\BClass;
use Project\Core\CClass;

use PHPUnit_Framework_MockObject_MockObject as MockObject;
```
